import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="w-full py-4 border-t border-gray-800 bg-quiz-dark mt-auto">
      <div className="container mx-auto px-4 text-center">
        <p className="text-gray-400">
          Content generated by an AI model. Please verify for accuracy before use.
        </p>
        
        <hr className="my-4 border-gray-600" />
        
        <p className="text-gray-400 mt-2">
          Crafted with 🤍 by{" "}
          <a
            href="https://abdullh.tech"
            target="_blank"
            rel="noopener noreferrer"
            className="text-white hover:text-quiz-primary transition-colors"
          >
            abdullh.tech
          </a>
        </p>
      </div>
    </footer>
  );
};

export default Footer;
